image:
  repository: gcr.io/hyperlane-labs-dev/hyperlane-monorepo
  tag:
hyperlane:
  runEnv: mainnet3
  context: hyperlane
nameOverride: ''
fullnameOverride: ''
# Allows statefulset updates to update pods in CrashLoopBackoff
podManagementPolicy: Parallel
