name: Hyperlane AVS Registration

on:
  push:
    branches: [main]
    paths:
      - 'typescript/**'
      - '.github/workflows/avs-registration.yml'
  pull_request:
    paths:
      - 'typescript/**'
      - '.github/workflows/avs-registration.yml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  LocalKeystore:
    name: register/deregister operator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Install less
        run: |
          sudo apt update
          sudo apt-get install less

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Fork Holesky
        run: |
          nohup anvil --fork-url https://ethereum-holesky-rpc.publicnode.com --fork-retry-backoff 3 > /tmp/anvil.log 2>&1 &
          cast bn

      - name: Install EigenLayer CLI
        run: |
          curl -sSfL https://raw.githubusercontent.com/layr-labs/eigenlayer-cli/master/scripts/install.sh | sh -s
          export PATH=$PATH:~/bin
          eigenlayer --version

      - name: Import Operator Keys and send funds
        run: |
          export PATH=$PATH:~/bin
          echo "" | eigenlayer operator keys import --key-type ecdsa --insecure opr0 ea25637d76e7ddae9dab9bfac7467d76a1e3bf2d67941b267edc60f2b80d9413 | cat
          cast send 0xcaB1b44dd1f1C265405878Ac1179cd94D0dBA634 --value 10ether --private-key 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6


